### ISSUE TITLE
Full PyPy support 

### ISSUE THREAD

**Issue by konstin** [PyO3/maturin#115]
pyo3-pack gets basic pypy support from #105, while some things are still missing.

 - [x] Add some automated testing, ideally on ci as pyo3 does.
 - [x] Figure out the best way to deal with manylinux.
   - [x] [pypy doesn't support maynlinux1](https://github.com/antocuni/pypy-wheels#why-not-manylinux1-wheels). manylinux2010 was [mentioned to be on the agenda of a pypy sprint meeting](https://morepypy.blogspot.com/2018/12/pypy-winter-sprint-feb-4-9-in-dusseldorf.html), however I couldn't find anything about the results.
   - [x] If we need to keep different defaults for pypy and cpython, the `Manylinux` enum should get a default variant so we can disambiguate whether a user requested `manylinux1` explicitly (i.e. we need to fail/skip pypy).
 - [x] Add windows support
   - [x] Find a reference how a native pypy wheel on windows should look like: `python_Levenshtein-0.10.2-pp38-pypy38_pp73-win_amd64.whl` contains `Levenshtein.pypy38-pp73-win_amd64.pyd`: https://paste.rs/ZAJ
 - [x] Test on mac (done by @messense, it works)
 - [x] ~~Skip pypy wheels when uploading~~
 - [x] Autodetect pypy binaries, but only for pyo3
 - [x] Look for a better way than using `SOABI` to determine the native extensions filename since that value isn't define on windows for both cpython and ~~pypy~~. `SOABI` is defined on windows for at least pypy 3.7 and later.
 - [x] #460

**Comment by mattip** [comment]
I got here from a [failing build of pywinpty](https://github.com/conda-forge/pywinpty-feedstock/pull/38) when rebuilding for PyPy3.7 and windows. The failure is [`ERROR: pywinpty-1.1.3-pp3pp73-pypy3_pp73-win_amd64.whl is not a supported wheel on this platform.`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=370519&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=0bf03e01-0bec-5b85-5316-b1633322e895&l=606) (link may dissapear in a week or so). The project uses `maturin build --release -i pypy3.7.exe`. 

Bottom line: The wheel name should end with `-pp37-pypy37_pp73-win_amd64.whl` not `-pp3pp73-pypy3_pp73-win_amd64.whl`. Any ideas where the extra `pp3` at the beninning is coming from?

Some additional comments: 
- *Add some automated testing, ideally on ci as pyo3 does:*
  [github actions setup-pythonv2](https://github.com/actions/setup-python#available-versions-of-pypy) supports pypy
- *Look for a better way than using SOABI to determine the native extensions filename since that value isn't define on windows for both cpython and pypy:*
  I think `sysconfig.get_config_var('SOABI') is the canonical way to do this. What versions of python do not support it? You could get some inspriation from the `pypa/wheel` [source code](https://github.com/pypa/wheel/blob/7ab18e4eb9ab30f60a82fad33357be666ca26637/src/wheel/bdist_wheel.py#L283)

**Comment by messense** [comment]
> Bottom line: The wheel name should end with -pp37-pypy37_pp73-win_amd64.whl not -pp3pp73-pypy3_pp73-win_amd64.whl. Any ideas where the extra pp3 at the beninning is coming from?

https://github.com/PyO3/maturin/blob/cb839bd9c8d3c5a3ef7fd64ed5a789f17e6e3d1a/src/python_interpreter.rs#L369

It comes from here.

**Comment by messense** [comment]
All done.
