### ISSUE TITLE
Fails to build for pure Rust projects using pyproject.toml

### ISSUE THREAD

**Issue by cnpryer** [PyO3/maturin#1281]
### Bug Description

A MWE with the following project structure will produce the result below.

```
├── Cargo.lock
├── Cargo.toml
├── pyproject.toml
└── src
    ├── bin
    │   └── main.rs
    └── example
        └── lib.rs
```

```
❯ maturin build
💥 maturin failed
  Caused by: Found a directory with the module name (example) next to Cargo.toml, which indicates a mixed python/rust project, but the directory didn't contain an __init__.py file.
```

### Your Python version (`python -V`)

Python 3.11.0

### Your pip version (`pip -V`)

pip 22.3

### What bindings you're using

bin

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Clone https://github.com/cnpryer/maturin-mwe
2. Install `maturin` with `pip`
3. Run `maturin build -b bin`

#1185 seems to add the src first layout for implying a python project dir. AFAIK this causes the failure I'm running into because I'm using a similar project structure for Rust code:

```
└── src
    └── example
        └── lib.rs
```

IIRC from tinkering, it fails with a pyproject.toml in the root of the repo. So it seems to imply it's a mixed project by default with a pyproject.toml used but the error is a little misleading since there is no `example` python module.

I'm assuming the way to opt out would be to remove usage of pyproject.toml and just update Cargo.toml with `[tool.maturin]`, but I haven't really looked into this yet. I can do that next. I did try slapping `-m Cargo.toml` in as a hail mary based on some of the conversation I saw from the PR.

**Comment by messense** [comment]
I took a look, it's not related to src-layout.

https://github.com/PyO3/maturin/blob/3cfd8869dfec0ea1b9c7420329afd12712b16bd5/src/project_layout.rs#L326-L341

It can't handle ATM because it assumes crate lives in `src/` not in its sub-directory.

```
src/
├── bin
└── huak
```

src-layout detection is pretty strict, you must have a `rust/Cargo.toml`.

**Comment by messense** [comment]
> it's not related to src-layout.

My bad, actually it's, there is a loose detection logic in https://github.com/PyO3/maturin/blob/3cfd8869dfec0ea1b9c7420329afd12712b16bd5/src/project_layout.rs#L145-L150

**Comment by messense** [comment]
@cnpryer You should remove `maturin-version: latest` now that `maturin-action` can [install the right version from `pyproject.toml`](https://github.com/PyO3/maturin-action/pull/46), it should resolve your issue for now because it will install maturin 0.13.x instead.

https://github.com/cnpryer/huak/blob/a4f5c64c7bb6dd7e6336b28e44f141f68d3323ba/.github/workflows/release.yaml#LL28C11-L28C34

**Comment by cnpryer** [comment]
Gotcha. I actually was about to bump it too. Thanks for the help!
