### ISSUE TITLE
1.3.0 release build failed to run against python 3.12

### ISSUE THREAD

**Issue by chenrui333** [PyO3/maturin#1812]
👋 While updating 1.3.0 release build to test against py3.12, I ran into some test failure as below:

```
  ==> /opt/homebrew/opt/python@3.12/libexec/bin/python -m pip install hello_world --no-index --find-links /private/tmp/maturin-test-20231021-9824-1x57z3t/dist
  error: externally-managed-environment
```

it ran out fine with py3.11 and 3.10

relates to https://github.com/Homebrew/homebrew-core/pull/151479

**Comment by konstin** [comment]
This is a problem in your test script: https://github.com/Homebrew/homebrew-core/pull/151479/files#diff-189e9514696b0323c6135c1e6c9d6205ac9aafa6744295375043deaf5190f720R67-R73 . Previously, pip would allow installing packages in the global environment, now they instead require you to use a virtualenv instead (fwiw that's a pip version thing not a python version thing, i think it's showing up now because python 3.12 updated the bundled pip).

**Comment by chenrui333** [comment]
I see, that makes sense. Thanks for the pointer.
