### ISSUE TITLE
Allow ignoring shared libraries

### ISSUE THREAD

**Issue by wiktor-k** [PyO3/maturin#1869]
Hi,

I'm using Maturin for my project and it works really well.

I've got an edge-case that (I believe) is not covered: sometimes I need the packaged wheel to *not* include an `so` in it but to use a host-system's version.

A live example from [a recent build](https://github.com/wiktor-k/pysequoia/actions/runs/6970834591/job/18969587392):

```
🖨  Copied external shared libraries to package pysequoia.libs directory:
    /usr/lib64/libpcsclite.so.1.0.0
    /usr/lib/libgmp.so.10.5.0
    /usr/lib64/libnettle.so.8.8
    /usr/lib64/libhogweed.so.6.8
```

All of them are fine with the exception of `/usr/lib64/libpcsclite.so.1.0.0`. PCSC communicates with a daemon running on user's system and the client `so` *needs* to be of the same exact version as the daemon (a problem described [here, with relation to flatpak](https://blog.apdu.fr/posts/2022/02/accessing-smart-cards-from-inside/)).

As far as I know it's not possible to ignore/exclude one library, but to include others.

Thanks for your time and help! :wave:

**Comment by konstin** [comment]
You can build such libraries using the native `linux` instead of the `manylinux` tag. You unfortunately can't upload those to pypi because pypi has a [policy](https://peps.python.org/pep-0513/#the-manylinux1-policy) about not allowing those, which we only replicate in maturin. As workaround, you could try load the dynamic library at runtime with [libloading](https://docs.rs/libloading/latest/libloading/) or a similar library.

**Comment by wiktor-k** [comment]
Okay, excellent points. I think I'll just go with higher compatibility (`manylinux2020`) for now, which won't solve the problem but will alleviate it for the time being. (Or even better, specify multiple compatibilities to increase the range of supported clients).

Thanks for your time, I'll close that issue as, I think, your answer paints a complete picture of available. options.

:wave:
