### ISSUE TITLE
Ability to specify `tool.maturin.source` similar to `tool.poetry.source`

### ISSUE THREAD

**Issue by osintalex** [PyO3/maturin#2070]
It would be useful to be able to specify sources as you can do in [poetry](https://python-poetry.org/docs/repositories/). This makes it much easier to ensure CI runs of packages install from correct package registries. 

I would want to use this to do things like installing from a PyPi mirror or a private package repository rather than having to make sure there is a correct `pip.conf` available.

I think it would also be useful to have corresponding [certificiates](https://python-poetry.org/docs/repositories/#certificates) support since it's likely many people will use custom certs for private packages hosted on internal networks.

**Comment by messense** [comment]
My feeling is that maturin is not a general purpose Python package manager like poetry so we'll probably not going to adding features related to managing complex dependencies.

**Comment by messense** [comment]
And I think as a PEP 517 build backend it's really out of our control when installing dependencies unless [PEP 508](https://peps.python.org/pep-0508/) allows specify package sources, since maturin can only write out the dependencies to [Core Metadata](https://packaging.python.org/en/latest/specifications/core-metadata/#requires-dist-multiple-use).
