### ISSUE TITLE
Unexpected python detection in `pip3 install .` for pyproject.toml.

### ISSUE THREAD

**Issue by 6br** [PyO3/maturin#277]
I'd like to run `pip3 install . -v` on the directory of a rust project with `pyproject.toml`. But it failed.

```
    💥 maturin failed
      Caused by: Failed to find python interpreter for generating cffi bindings
      Caused by: Failed to get information from the python interpreter at python
      Caused by: Only python python >= 3.5 is supported, while your using python 2.7
    Checking for Rust toolchain....
    Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-nn0v_ecx --bindings=cffi --manylinux=off`
    Error: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-nn0v_ecx', '--bindings=cffi', '--manylinux=off']' returned non-zero exit status 1.
    Preparing wheel metadata ... error
```

The reason seems simple. There is two binary on paths on the system, `python` for python2 binary and `python3` for python3 binary.  I'd like to install the rust project on host environment, not on virtualenv. The marurin system detects python2 because of `python` links ython2 binary, and it fails.

So I hope that the maturin automatically detects python3 binary. Is it possible?

**Comment by konstin** [comment]
I suppose the problem that maturin currently unconditionally uses `python` in the PEP517 interface instead of passing `sys.executable` from the python part to the rust part.

**Comment by WayneWayner** [comment]
I get a similar error. Creating an alias to make python to python3 does not change anything. I am trying to build on ARM CPU (RPI 4).

`python --version
Python 2.7.16
`
~/.bashrc
`alias python=python3`

`python --version
Python 3.7.3
`


`
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
💥 maturin failed
  Caused by: The given list of python interpreters is invalid
  Caused by: python is not a valid python interpreter
  Caused by: Failed to get information from the python interpreter at python
  Caused by: Only python >= 3.5 is supported, while your using python 2.7
`

**Comment by hombit** [comment]
I tried to add `"-i", sys.executable,` to the following part of code, but I still have the same error as discussed above
https://github.com/PyO3/maturin/blob/5ef33e4e9e01b1d0d1c4d9a8c68124a289e791af/maturin/__init__.py#L125-L131

@konstin, do you have any ideas how it can fixed?
