### ISSUE TITLE
Support for cargo workspaces

### ISSUE THREAD

**Issue by g-braeunlich** [PyO3/maturin#291]
In `test-crates` there is an example `lib_with_path_dep` referencing `some_path_dep`. However this example does not provide a `pyproject.toml` and also an own attempt to build such a project with `pip install .` fails for me.
My idea here would be to add support for cargo workspaces:
https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html
Basically this would mean: you have a top level project dir with a cargo.toml only specifying its members in the above example `lib_with_path_dep` and `some_path_dep`).
I would then put the section `[package.metadata.maturin]` into this file as `[workspace.metadata.maturin]` and also introduce a new field `workspace.metadata.maturin.extension(s)` specifying which of the members is a / the crate containing the pyO3 extension.
For mixed projects, the python code would now go to the toplevel directory together with (pyproject.toml / README.md).
What do you think?

**Comment by konstin** [comment]
FYI, the two crates in `test-crates` exist to test that is shown when using local (including workspace) dependencies as a test for https://github.com/PyO3/maturin/issues/238. Also note that `maturin develop` and `maturin build` work fine, only source distributions are affected.

I think the most user friendly solution would be calling `cargo package --list` on each linked or transitively linked package in the workspace and adding them to the source distribution (This information is part of the `cargo metadata` output). If the root package is not directly in the workspace root than the location of the root package needs to be recorded somewhere, e.g. by adding a metadata key the workspace root `Cargo.toml`.

**Comment by clbarnes** [comment]
Somewhat related: my use case is a cargo workspace including a rust crate (for crates.io) and a pyo3-based wrapper using maturin, which is a mixed project and has a local dependency on the other crate. I'm trying to version them independently, but publishing with maturin produces an sdist which has a remote dependency on the published crate, and a wheel which packages the compiled result of the local dependency: potentially two different versions of the crate.

I think that either way (use the local, or use the published) would be fine (or could be worked around) so long as sdist and bdist were consistent.

**Comment by tari** [comment]
I recently had similar problems. I wanted to build a crate with multiple bindings in a workspace, something like:

* Cargo.toml (workspace)
* base/Cargo.toml (Rust core with external dependencies)
* py/Cargo.toml (Python extension module, depends on `base = { path = "../base" }`)
* wasm/Cargo.toml (WASM bindings, depends on base)

While I was able to build wheels from in the `py` directory, maturin isn't able to build a sdist that works due to the path dependency. For now I've opted to use `setuptools-rust` instead since I can specify the path to the extension to build separately from the package root for sdist. (It also allows me to use different module and crate names, like #391.)

**Comment by tafia** [comment]
using `maturin -m py/Cargo.toml` seems to work for me.

**Comment by konstin** [comment]
Should be fixed by #441. Could you check whether v0.10.0-beta.1 works for you?

**Comment by tari** [comment]
It seems to be looking for lockfiles that don't necessarily exist here. With the same layout as https://github.com/PyO3/maturin/issues/291#issuecomment-758328862 and lightly anonymized:

```
$ maturin --version
maturin 0.10.0-beta.1
$ maturin build -m py/Cargo.toml
🔗 Found pyo3 bindings
🐍 Found CPython 3.9 at python3.9
💥 maturin failed
  Caused by: Failed to build source distribution
  Caused by: Failed to add local dependency PACKAGE at .../base to the source distribution
  Caused by: Failed to add file from .../base/Cargo.lock to sdist as PACKAGE/local_dependencies/PACKAGE/Cargo.lock
  Caused by: No such file or directory (os error 2) when getting metadata for .../base/Cargo.lock
```

I have one Cargo.lock file next to the workspace's Cargo.toml, and created `py/pyproject.toml` so it will create an sdist. If no sdist is built, then things still seem to work (but of course there's no sdist).

**Comment by MrNickArcher** [comment]
I tried and concluded that Maturin does not work with workspaces, I got it to build after messing with the configuration files for ages. But there are so many other small issues regarding package names vs crate names; the .pyd file doesnt get copied where it should; the `mypackage.XXX.dist-info` folder name does match the `package` folder in .env/Lib. Overall a bad time was had and I went back to the recommended package layout. A bit sad because it makes life hard if I want to concurrently develop python bindings alongside one or more reusable rust libraries.

**Comment by dantliff-sqc** [comment]
For what it's worth, I was able to get `maturin build` to work for an individual crate in a cargo workspace by first changing to the directory of the crate's `Cargo.toml`, and run `maturin` from there. It seems to look back up the directory tree to find the workspace's root `Cargo.toml` without issue.

E.g.

```
$ cd py/my_pyo3_project/
$ maturin build
```

This also works for multiple PyO3 crates in the same workspace, just `cd` into the one you want to build.

I need to do this because I'm using Yocto to build my crates, and the `python_maturin` bbclass doesn't support `-m` syntax, so instead I set the source directory `S` variable to:

```
S = "${WORKDIR}/workspace/py/my_pyo3_project"
```

This is equivalent to running `maturin` from the `my_pyo3_project` directory itself.
