### ISSUE TITLE
README path on windows

### ISSUE THREAD

**Issue by g-braeunlich** [PyO3/maturin#292]
When using maturin on appveyor on a project structured like

```
workspace
 ├── README.md
 ├── pure_rust_lib
 └── pyo3_lib (dependent on pure_rust_lib)
          └── Cargo.toml
```
where, `pyo3_lib/Cargo.toml` contains
```
[package]
readme = "../README.md"
```
Then running `maturin publish / build`  in the folder `pyo3_lib` fails:

```
maturin.exe publish -u user
maturin.exe : ≡ƒÆÑ maturin failed
At line:2 char:1
+ maturin.exe publish -u user
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (≡ƒÆÑ maturin failed:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  Caused by: Failed to parse Cargo.toml into python metadata
  Caused by: Failed to read readme specified in Cargo.toml, which should be at \\?\C:\projects\workspace\pyo3_lib\../README.md
  Caused by: 
The filename, directory name, or volume label syntax is incorrect.
 (os error 
123
)
```

I guess it is due to `/`. However, changing `/` to `\\` in `Cargo.toml` did not solve the problem for me.
I had to copy / move README.md into the pyo3_lib folder and remove `../` in `Cargo.toml`.

**Comment by programmerjake** [comment]
That's caused by whatever windows filesystem calls it's using using the `\\?\` prefix which disables handling all of `..` path segments, `.` path segments, and `/` to `\` conversion.
See [the Win32 API docs](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) (search the page for `\\?\`).

**Comment by konstin** [comment]
Thanks @programmerjake, those docs are really helpful!

Apparently the root issue is that `Path::canonicalize` adds the prefix on windows, because that's what windows considers canonical (https://github.com/rust-lang/rust/issues/42869). This seems to affect a lot of projects, which either solve this by stripping away the prefix or not joining on cwd instead of canonicalizing, including [wasm-pack](https://github.com/rustwasm/wasm-pack/pull/389) and [dtolnay's cxx](https://github.com/dtolnay/cxx/pull/41/files#diff-dd3f6b38e4d718f4e814207fe21e2dadR85-R97). I had already been bitten by that in the tests because pip didn't like the prefix, where I could solve this with [shepmaster's stack overflow solution](https://stackoverflow.com/a/50323079/3549270)

**Comment by messense** [comment]
I think it's already fixed in https://github.com/PyO3/maturin/pull/510 , feel free to reopen if it still occurs.
