### ISSUE TITLE
When cargo building pyo3 projects auto-add in the extension-module feature please

### ISSUE THREAD

**Issue by gilescope** [PyO3/maturin#325]
At the moment maturin warns if a pyo3 project is built without the extension-module feature.

We can already do:

maturin develop --cargo-extra-args="--features pyo3/extension-module"

Why not add that flag in automatically if it's clear that it's not there? Having pyo3/extension-module turned on as a default feature seems like a footgun as people will just run cargo test and expect stuff to work on cli, IDEs etc. but will run into linking problems if they don't use --no-default-features. It's both unergonomic and confusing as the linker errors give no clue that you should have disabled a feature so it's tough on new users.

It would be great if maturin just by default did the right thing :-) - 
(it could still squark that it wasn't found so adding it in explicitly.)

thoughs?

**Comment by davidhewitt** [comment]
I think that's a very good idea!

**Comment by konstin** [comment]
Blocked on https://github.com/PyO3/pyo3/pull/1040 being resolved.

**Comment by messense** [comment]
After #605 lands, you can add the `cargo-extra-args = "--features pyo3/extension-module"` to the `[tool.maturin]` section in `pyproject.toml` and maturin will pick it up automatically.

**Comment by konstin** [comment]
I believe `[tool.maturin] cargo-extra-args` in is the way to go

**Comment by jmhodges** [comment]
Reading between the lines here, I think this issue closing means we could take an update to [getting_started.md](https://github.com/PyO3/pyo3/blob/4d80475008801c428dc0dd74c4aefaa2be447ee3/guide/src/getting_started.md#pyprojecttoml)'s examples and maybe to the [FAQ](https://github.com/PyO3/pyo3/blob/4d80475008801c428dc0dd74c4aefaa2be447ee3/guide/src/faq.md#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror) to allow folks to run `cargo test` work out of the box

I'm willing to do that, would like to confirm what's desired.

I think what we want is the example `pyproject.toml` to gain a

```toml
[tool.maturin]
features = ["pyo3/extension-module"]
```

while the example `Cargo.toml`'s `dependencies` looks like:

```toml
[dependencies]
pyo3 = "0.18.0"
```

(Or I could be convinced to make that `pyo3 = { version = "0.18", features = ["anyhow"] }` since that's so handy)

**Comment by jmhodges** [comment]
I could also be convinced that the recommended set up would be better as the mixed Python and Rust code per [the maturin guide](https://github.com/PyO3/maturin/blob/main/guide/src/project_layout.md#alternate-python-source-directory-src-layout). I could be convinced since being able to write Python tests out of the box make it easier to ensure the Python API is ergonomic, while allowing `cargo test` and other `cargo` tools to work is useful for IDEs and rust analysis tools.

**Comment by messense** [comment]
> I could also be convinced that the recommended set up would be better as the mixed Python and Rust code

You can generate a mixed Python/Rust project with `maturi new --mixed`.

**Comment by messense** [comment]
> Reading between the lines here, I think this issue closing means we could take an update to [getting_started.md](https://github.com/PyO3/pyo3/blob/4d80475008801c428dc0dd74c4aefaa2be447ee3/guide/src/getting_started.md#pyprojecttoml)'s examples and maybe to the [FAQ](https://github.com/PyO3/pyo3/blob/4d80475008801c428dc0dd74c4aefaa2be447ee3/guide/src/faq.md#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror) to allow folks to run `cargo test` work out of the box

Pull requests are welcome, I think we can also update the `maturin new/init` template: https://github.com/PyO3/maturin/blob/46f4b1a0c1e4583de998467e8579ad2b69a0d685/src/templates/Cargo.toml.j2#L14-L15
