### ISSUE TITLE
PowerPC64LE support

### ISSUE THREAD

**Issue by programmerjake** [PyO3/maturin#366]
Wheel name `numpy-1.19.2-cp38-cp38-linux_ppc64le.whl`
`.so` name `lapack_lite.cpython-38-powerpc64le-linux-gnu.so`

[python-sysconfig.txt](https://github.com/PyO3/maturin/files/5424532/python-sysconfig.txt)

I have to install maturin using:
```bash
cargo install maturin --no-default-features --features=auditwheel,log,human-panic
```
since ring doesn't support powerpc64le-unknown-linux-gnu: https://github.com/briansmith/ring/issues/389#issuecomment-711801345

**Comment by mzpqnxow** [comment]
@programmerjake I have the same issue and have been watching the AES-GCM issue since April :/

I only have a dependency on `maturin` because of the inclusion of `orjson` in one of my projects. It's not entirely clear to me how to install the `maturin` Python, though I did install `maturin` rust via `cargo`. Can you give me a pointer as to what needs to be done to get the `maturin` Python package to install after this, so I can get past this dependency? Or maybe I'm misunderstanding and you're still blocked as well?

I'm looking at the `setuptools` `setup.py` and I see the invocation of:

```
["cargo", "rustc", "--bin", "maturin", "--", "-C", "link-arg=-s"]
```

Do I need to replace this?

Thanks for any help you can provide, I have nearly zero experience with rust/cargo as you can probably guess...

**Comment by mzpqnxow** [comment]
I tried replacing the `check_call` arguments in `setup.py` with:

```
                ["cargo", "rustc", "--bin", "maturin", "--", "-C", "link-arg=-s", '--no-default-features', '--features=auditwheel,log,human-panic']
```

But no luck, same error. I also pulled the latest stable rustc, same issue:

```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```

**Comment by mzpqnxow** [comment]
@programmerjake I think I figured it out.. sorry for bugging you ;)

I ended up using your command to install maturin, then commenting out the `check_call` in `setup.py`, then modifying the path in the file copy function to point at the `maturin` that was already installed and that seems to take care of it..

**Comment by mzpqnxow** [comment]
For anyone else having this issue, a more explicit explanation of the solution from @programmerjake 

```
$ cat > maturin-setuptools.patch << 'EOF'
--- ../setup.py	2020-08-17 14:47:52.000000000 +0000
+++ setup.py	2020-10-24 21:25:06.074357597 +0000
@@ -56,9 +56,10 @@
                     "(https://www.rust-lang.org/tools/install) and try again"
                 )
             subprocess.check_call(
-                ["cargo", "rustc", "--bin", "maturin", "--", "-C", "link-arg=-s"]
-            )
+                 ['cargo', 'install', 'maturin', '--no-default-features', '--features=auditwheel,log,human-panic'])
             source = os.path.join(source_dir, "target", "debug", executable_name)
+            source = os.path.join(os.getenv('HOME'), '.cargo', 'bin', 'maturin')
+
         # run this after trying to build with cargo (as otherwise this leaves
         # venv in a bad state: https://github.com/benfred/py-spy/issues/69)
         install.run(self)
EOF
$ pip download maturin==0.8.3  # or whatever version you need- orjson wants 0.8.3<0.9
$ mkdir build-maturin && cd build-maturin && tar -xvzf ../maturin-0.8.3.tar.gz
$ patch -p1 < ../maturin-setuptools.patch
$ pip install .
```

Thanks again @programmerjake for the help, I thought I was stuck until the AES-GCM code was fixed in ring :)

**Comment by mzpqnxow** [comment]
@programmerjake so I was able to get what I needed working (though it required a lot more hacking on the package I was building, which had a dependency on `simd` - at least I learned some rust ..) but I needed to make a patch to run-time logic in `maturin` because it refused to attempt to build anything without adding explicit "support" for `ppc64le`

I put in a PR (#367) that patches the run-time architecture check in case it's helpful to you. That change (plus the one in `setup.py`) was enough to be able to successfully build `orjson` (and it works)

**Comment by konstin** [comment]
Does #367 fix this?

**Comment by programmerjake** [comment]
Yes, though not completely, we're still blocked on `ring` gaining PowerPC64LE support, since that's required for enabling all the default features.

**Comment by mzpqnxow** [comment]
> Yes, though not completely, we're still blocked on `ring` gaining PowerPC64LE support, since that's required for enabling all the default features.

And I'm not expecting that being resolved any time soon. That AES thread has been open for quite a while and seems to have stalled out :/

Though the current state of things works well enough for me

**Comment by mzpqnxow** [comment]
@konstin are you planning on releasing 0.9.0b1 to PyPi? Or are you waiting until you have a stable 0.9 release?

**Comment by konstin** [comment]
Sorry it took so long, but there's a stable 0.9.0 release now

**Comment by mzpqnxow** [comment]
Thanks!
