### ISSUE TITLE
auditwheel check should pass on default

### ISSUE THREAD

**Issue by konstin** [PyO3/maturin#448]
Currently, `maturin build` will fail on most machines because they are not manylinux2010 compliant. The default should either be changed to `off` or to autodetect the lowest possible manylinux version before the final 0.10.0 release.

**Comment by messense** [comment]
Autodetect lowest possible manylinux version is possible, but on non manylinux2010/2014 compliant machines `maturin build` would still fail. I think the it's ok to fail with `maturin build` because you just shouldn't distribute wheels built on non manylinux compliant machines. For local development, people should prefer `maturin develop` over `maturin build`. But we certainly should improve the error message a little to tell user to use  the `--manylinux off` option.

**Comment by messense** [comment]
Or we can add a `auto` choice for `--manylinuux` and switch default to `off` and autodetect lowest possible manylinux version with `--manylinux auto`
