### ISSUE TITLE
.so file is not included in wheel

### ISSUE THREAD

**Issue by wangxiaoying** [PyO3/maturin#911]
### Bug Description

I need to include a dynamic library as dependency to the wheel file. It works fine when I build for mac where the library is named "xxx.dylib". But when I build for linux, the corresponding dynamic library (xxx.so) is not packed in the wheel file. If I copy the `xxx.so` file and rename it to another suffix like `xxx.so.1` or `xxx.dylib`, it will be packed in wheel.

I also try remove my `.gitignore` entirely file and rebuild but it is still not packed.

```
mylib
├── __init__.py
├── mylib.cpython-38-x86_64-linux-gnu.so
├── dependencies
│   ├── deps
│   │   ├── libj4rs-56a493ea0de46c1b.so     - this file is not packed in wheel
│   │   └── libj4rs-56a493ea0de46c1b.so.1   - this file is packed in wheel
│   ...
```

### Your Python version (`python -V`)

3.8

### Your pip version (`pip -V`)

22.0.3

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. maturin build --release -i python --no-sdist

**Comment by messense** [comment]
This is by design, you should not include arbitrary shared libraries since they may not work on target platform. Instead you should link to them dynamically and let [`auditwheel`](https://github.com/pypa/auditwheel) to bundle them. Maturin already reimplemented auditwheel feature in Rust for Linux, but lacks support for [macOS](https://github.com/matthew-brett/delocate) and [Windows](https://github.com/adang1345/delvewheel) right now.

https://github.com/PyO3/maturin/blob/6b5c8735bfae8c05091d71cf2ca8a09aa7c0a587/src/module_writer.rs#L791-L795

**Comment by wangxiaoying** [comment]
Hi @messense , ic,  thanks for the quick response!
