### ISSUE TITLE
`maturin develop` failed on Windows because of utf-8 encoding error

### ISSUE THREAD

**Issue by bachue** [PyO3/maturin#952]
### Bug Description

I'm developing a PyO3 project. Actually this project works well on Linux / Mac, but failed on Windows 10.

![Untitled](https://user-images.githubusercontent.com/321962/172095172-a27d02bb-c94e-45c8-a5a7-31b4aaa24d65.png)

I have no idea which file includes invalid utf-8 character.

### Your Python version (`python -V`)

python 3.10.4

### Your pip version (`pip -V`)

pip 22.1.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

Run these commands on Powershell

```pwsh
git clone git@github.com:bachue/rust-sdk-python-bindings.git
cd rust-sdk-python-bindings
.\.env\Scripts\Activate.ps1
.\.env\Scripts\python.exe -m pip install pip --upgrade
.\.env\Scripts\python.exe -m pip install ".[tests]"
maturin.exe develop
```

Then failed just like the snapshot.

**Comment by messense** [comment]
I think the error may caused by one of the following lines

https://github.com/PyO3/maturin/blob/bc15baf5281d9cd9fbe424f0e6e1e1857edc0178/src/develop.rs#L94
https://github.com/PyO3/maturin/blob/bc15baf5281d9cd9fbe424f0e6e1e1857edc0178/src/develop.rs#L95
https://github.com/PyO3/maturin/blob/bc15baf5281d9cd9fbe424f0e6e1e1857edc0178/src/develop.rs#L102

Could you debug it? I don't have a reproducible Windows environment.

**Comment by bachue** [comment]
![image](https://user-images.githubusercontent.com/321962/172125657-f9e87578-7240-4b46-8ca9-3e0cf3cc838d.png)
Ok, I got the reason now, running PowerShell with Administrator could resolve it.

**Comment by messense** [comment]
Reopening because we should provide a better error message.
