### ISSUE TITLE
`maturin publish` always "Username and/or password are wrong"

### ISSUE THREAD

**Issue by RiotGamesU** [PyO3/maturin#999]
### Bug Description

```shell
(.env) root@instance:~/a# maturin publish -u aaaa -p aaaaaaaa
🔗 Found bin bindings
    Finished release [optimized] target(s) in 0.12s
📦 Built wheel to /root/a/target/wheels/a-0.1.8-py3-none-manylinux_2_28_aarch64.whl
🚀 Uploading 1 packages
⛔ Username and/or password are wrong
💥 maturin failed
  Caused by: Username and/or password are wrong
(.env) root@instance:~/a# 
```

always

pypi.org "Security history":

```
Login failed - Basic Auth (Upload endpoint)
Reason: Incorrect Password
```

### Your Python version (`python -V`)

Python 3.8.10

### Your pip version (`pip -V`)

pip 20.0.2 from /root/a/.env/lib/python3.8/site-packages/pip (python 3.8)

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

```shell
maturin publish -u aaaa -p aaaaaaaa
```

tried use "Api Token":

```shell
maturin publish -u __token__ -p pypi-xxxx
```

**Comment by RiotGamesU** [comment]
After testing, the duplicate package name will report the above error, I do not know why this, maturin and pypi.org will show a password error

**Comment by messense** [comment]
You can open an issue in https://github.com/pypi/warehouse/issues since the error message is from pypi.

**Comment by nednoodlehead** [comment]
This problem seems to be solved for the most part.
I create a new account (used a very different password)
Tried to publish, 502 error.
Tried to publish again, success

I wont gaslight myself into thinking I typed my password in wrong. This isn't my first day on Earth. I was typing it in right.
However, trying:
import pungedataclean as dc
after pip installing it gives a module not found though
